-- MySQL Script generated by MySQL Workbench
-- Sat Dec 19 18:30:56 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema store_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema store_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `store_db` DEFAULT CHARACTER SET utf8 ;
USE `store_db` ;

-- -----------------------------------------------------
-- Table `store_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_db`.`users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `phone` VARCHAR(45) NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `store_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_db`.`products` (
  `id_product` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `title` VARCHAR(45) NOT NULL,
  `image_link` VARCHAR(200) NULL,
  `price` FLOAT NOT NULL,
  PRIMARY KEY (`id_product`),
  INDEX `id_user_idx` (`user_id` ASC),
  CONSTRAINT `id_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `store_db`.`users` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
